name: Deploy Aki Chatbot

on:
  push:
    branches:
      - main  # Chạy workflow khi có push lên branch main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Sử dụng Node.js 16

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./client

      - name: Build frontend
        run: npm run build
        working-directory: ./client
        env:
          CI: ""

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
          
  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Heroku # Deploy backend lên Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "your-heroku-app-name" # Thay bằng tên app Heroku của bạn
          heroku_email: "your-heroku-email" # Thay bằng email Heroku của bạn
          procfile: "web: node backend/index.js" # Cấu hình Procfile
          appdir: "backend" # Chỉ định thư mục backend