name: Deploy Aki Chatbot

on:
  push:
    branches:
      - main

jobs:
  create-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Check if gh-pages exists
        id: check_gh_pages
        run: |
          if git ls-remote --exit-code --heads origin gh-pages; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Create gh-pages branch if it doesn't exist
        if: steps.check_gh_pages.outputs.exists == 'false'
        run: |
          git checkout main
          git checkout -b gh-pages
          git push --set-upstream origin gh-pages

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: create-gh-pages
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # or specify a version

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./client

      - name: Build frontend
        run: npm run build
        working-directory: ./client

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build

  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # or specify a version

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}