name: Deploy Aki Chatbot

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Sử dụng phiên bản LTS mới nhất

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./client

      - name: Build frontend
        run: npm run build
        working-directory: ./client
        env:
          CI: ""

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build

  deploy-backend:
    runs-on: ubuntu-latest
    # needs: deploy-frontend # Cân nhắc bỏ nếu không cần thiết
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js # Thêm setup Node.js cho backend nếu cần
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install backend dependencies # Thêm bước cài đặt dependencies cho backend nếu cần
        run: npm install
        working-directory: ./server # Thay đổi đường dẫn nếu backend không nằm trong thư mục 'server'

      - name: Build backend # Thêm bước build cho backend nếu cần
        run: npm run build # Thay đổi câu lệnh build phù hợp với dự án
        working-directory: ./server # Thay đổi đường dẫn nếu backend không nằm trong thư mục 'server'

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          api-key: ${{ secrets.RENDER_API_KEY }} # Sử dụng GitHub Secrets
          service-id: ${{ secrets.RENDER_SERVICE_ID }} # Sử dụng GitHub Secrets