name: Deploy Aki Chatbot

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main  # Checkout branch main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./client

      - name: Build frontend
        run: npm run build
        working-directory: ./client
        env:
          CI: ""
          NODE_OPTIONS: "--openssl-legacy-provider"

      - name: Check if gh-pages exists
        id: check_gh_pages
        run: |
          git fetch origin gh-pages:gh-pages
          if [ $? -eq 0 ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Create gh-pages branch if it doesn't exist
        if: steps.check_gh_pages.outputs.exists == 'false'
        run: |
          git checkout main # Chắc chắn đang ở branch main
          git checkout -b gh-pages # Tạo gh-pages từ main
          git push --set-upstream origin gh-pages # Push và theo dõi branch

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages  # Checkout branch gh-pages
          path: gh-pages # Clone vào thư mục gh-pages

      - name: Copy build files to gh-pages root
        run: |
          rm -rf ./gh-pages/*  # Xóa toàn bộ nội dung trong thư mục gh-pages
          mkdir -p gh-pages # Đảm bảo thư mục gh-pages tồn tại
          cp -r ./client/build/* ./gh-pages/ # Copy nội dung từ client/build vào gh-pages

      - name: Commit and push to gh-pages branch
        run: |
          cd gh-pages
          git config user.email "youremail@example.com"  # Thay bằng email của bạn
          git config user.name "Your Name"  # Thay bằng tên của bạn
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages

  deploy-backend:
    runs-on: ubuntu-latest
    # needs: deploy-frontend # Bỏ comment nếu deploy backend cần deploy frontend thành công
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}