name: Deploy Aki Chatbot

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./client

      - name: Build frontend
        run: npm run build
        working-directory: ./client
        env:
          CI: ""
          NODE_OPTIONS: "--openssl-legacy-provider" # Fix lỗi OpenSSL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build # Đảm bảo là ./client/build
          # cname: example.com # Optional: Nếu bạn dùng custom domain

  deploy-backend:
    runs-on: ubuntu-latest
    # needs: deploy-frontend # Bỏ comment nếu deploy backend cần deploy frontend thành công
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}